export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const GET_APIS_BY_PROJECTID = 'GET_APIS_BY_PROJECTID'
export const GET_DETAIL_BY_APIID = 'GET_DETAIL_BY_APIID'
